name       : graphicsmagick
version    : 1.3.26
release    : 11
source     :
    - http://internode.dl.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.26/GraphicsMagick-1.3.26.tar.xz : fba015f3d5e5d5f17e57db663f1aa9d338e7b62f1d415b85d13ee366927e5f88
license    :
    - MIT
    - BSD-2-Clause
component  : multimedia.graphics
summary    : GraphicsMagick provides a set of commandline tools and programming APIs
    for manipulating, editing, and converting raster and vector images.
description: |
    GraphicsMagick provides a set of commandline tools and programming APIs for manipulating, editing, and converting raster and vector images. It is derived from ImageMagick, with the objective of providing better stability and performance than ImageMagick.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(x11)
    - bzip2-devel
    - libjpeg-turbo-devel
setup      : |
    %apply_patches
    %configure --disable-static --enable-shared=yes --with-modules --with-quantum-depth=16
build      : |
    %make
install    : |
    %make_install
    find $installdir/usr -name "*.la" | xargs -I{} dirname {} | uniq | sort | xargs -I{} libtool --finish {}
