name       : graphicsmagick
version    : 1.3.31
release    : 17
source     :
    - http://ftp.icm.edu.pl/pub/unix/graphics/GraphicsMagick/1.3/GraphicsMagick-1.3.31.tar.xz : 096bbb59d6f3abd32b562fc3b34ea90d88741dc5dd888731d61d17e100394278
license    :
    - MIT
    - BSD-2-Clause
component  : multimedia.graphics
summary    : GraphicsMagick provides a set of commandline tools and programming APIs for manipulating, editing, and converting raster and vector images.
description: |
    GraphicsMagick provides a set of commandline tools and programming APIs for manipulating, editing, and converting raster and vector images. It is derived from ImageMagick, with the objective of providing better stability and performance than ImageMagick.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(x11)
    - bzip2-devel
lastrip    : no
setup      : |
    %configure --disable-static \
               --enable-shared=yes \
               --with-modules \
               --with-quantum-depth=16
build      : |
    %make
install    : |
    %make_install
