name       : graphicsmagick
version    : 1.3.21
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.21/GraphicsMagick-1.3.21.tar.xz : 9045304d991776b6a37e1b45b9b6ef152593ada0d49bc744263565617cbf3c1f
license    :
    - MIT
    - BSD-2-Clause
component  : multimedia.graphics
summary    : GraphicsMagick provides a set of commandline tools and programming APIs
    for manipulating, editing, and converting raster and vector images.
description: |
    GraphicsMagick provides a set of commandline tools and programming APIs for manipulating, editing, and converting raster and vector images. It is derived from ImageMagick, with the objective of providing better stability and performance than ImageMagick.
builddeps  :
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(x11)
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static --enable-shared=yes
build      : |
    %make
install    : |
    %make_install
