name       : graphicsmagick
version    : 1.3.25
release    : 9
source     :
    - http://internode.dl.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.25/GraphicsMagick-1.3.25.tar.xz : d64bfa52d2e0730eff9ce3ed51d4fc78dbb68e2adaa317b2bb3c56e6ee61ac9f
license    :
    - MIT
    - BSD-2-Clause
component  : multimedia.graphics
summary    : GraphicsMagick provides a set of commandline tools and programming APIs
    for manipulating, editing, and converting raster and vector images.
description: |
    GraphicsMagick provides a set of commandline tools and programming APIs for manipulating, editing, and converting raster and vector images. It is derived from ImageMagick, with the objective of providing better stability and performance than ImageMagick.
builddeps  :
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(x11)
    - libjpeg-turbo-devel
setup      : |
    %apply_patches
    %configure --disable-static --enable-shared=yes --with-modules --with-quantum-depth=16
build      : |
    %make
install    : |
    %make_install
