name       : graphicsmagick
version    : 1.3.27
release    : 13
source     :
    - https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/1.3.27/GraphicsMagick-1.3.27.tar.xz : d03278d2790efc1dc72309f85a539810d2a81deb47932f7e6720d09ac72d0367
license    :
    - MIT
    - BSD-2-Clause
component  : multimedia.graphics
summary    : GraphicsMagick provides a set of commandline tools and programming APIs for manipulating, editing, and converting raster and vector images.
description: |
    GraphicsMagick provides a set of commandline tools and programming APIs for manipulating, editing, and converting raster and vector images. It is derived from ImageMagick, with the objective of providing better stability and performance than ImageMagick.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(x11)
    - bzip2-devel
    - libjpeg-turbo-devel
setup      : |
    %apply_patches
    %configure --disable-static --enable-shared=yes --with-modules --with-quantum-depth=16
build      : |
    %make
install    : |
    %make_install
    find $installdir/usr -name "*.la" | xargs -I{} dirname {} | uniq | sort | xargs -I{} libtool --finish {}
